### ISSUE TITLE
Blender 3.1 and Animation Node new version compatibility ssue maybe?

### ISSUE THREAD

**Issue by LionGartGithubPage** [harisreedhar/an_bluefox_extension#10]
Hello there. I really love your extention and used it a lot in my old blender projects. How ever when I am upgrading to newer version of blender and latest version of Animation Node Addon. I found that your latest Animation Node extention seams to have lost some link to previous moduls. I have attach the error that comes up when I try to reinstall the addon. I want to kindly ask your help if you might share some solutions or possible update. Thank you.

![Screenshot 2022-02-02 095629](https://user-images.githubusercontent.com/77560129/152086992-689c5101-f604-4a6c-89bd-a0a2dfc39680.png)

**Comment by harisreedhar** [comment]
@LionGartGithubPage Glad to hear that extension was useful in your projects. 
Yesterday i upgraded developmental build to python 3.10. You can download it from [releases](https://github.com/harisreedhar/an_bluefox_extension/releases/tag/master-cd-build) (ending with py310).
Let me know if it works or not :)

**Comment by LionGartGithubPage** [comment]
@harisreedhar Thank you for the response and answer. I tried the new version and it works. Thank you very much.
