### ISSUE TITLE
Bug report: Spline Tracer does not work well

### ISSUE THREAD

**Issue by Shompinice** [harisreedhar/an_bluefox_extension#11]
What it should be

https://user-images.githubusercontent.com/105156967/167431636-818347a3-cfd0-4530-9eb5-d63605e387c4.mp4

What it is in my Blender

https://user-images.githubusercontent.com/105156967/167432016-b1c56f33-7a8c-4531-b4cb-73ada7189bc5.mp4

The blender file
[test.zip](https://github.com/harisreedhar/an_bluefox_extension/files/8652599/test.zip)

**Comment by harisreedhar** [comment]
@Hardiol The bug has been fixed. Please reinstall the extension and try again. Thanks for the report.
