### ISSUE TITLE
Bug report：messy polylines

### ISSUE THREAD

**Issue by Shompinice** [harisreedhar/an_bluefox_extension#12]
![image](https://user-images.githubusercontent.com/105156967/167668742-41b0a1c4-ee01-4eb6-bd3a-2da1feacb41b.png)

How it looks without line（curve）
![image](https://user-images.githubusercontent.com/105156967/167670328-69999be9-b608-4bb6-b2c2-75131dbf88f7.png)

What that happen？

the number of particle，500000
but it still run in a wrong way even if I change the number to 1000

You must bake before capture the move of particle
![image](https://user-images.githubusercontent.com/105156967/167670496-04db703e-5a8f-44a7-87be-2616f6b446de.png)

the file
https://drive.google.com/file/d/1rxpFkH8mUpOAswRtoaEZN3mw4AuTEuZv/view?usp=sharing

**Comment by harisreedhar** [comment]
@Hardiol It is not a bug but a limitation. The particles are being killed randomly during simulation, so tracer can't create spline from inconsistent data.
