### ISSUE TITLE
Bug report : install error

### ISSUE THREAD

**Issue by Shompinice** [harisreedhar/an_bluefox_extension#13]
![image](https://user-images.githubusercontent.com/105156967/168406097-c85c0bab-2c08-451e-8be8-44e54c10edfc.png)

Blender Version 3.0.0
Plugin Version 
[an_bluefox_extension_v1_2_windows_py39.zip](https://github.com/harisreedhar/an_bluefox_extension/files/8691948/an_bluefox_extension_v1_2_windows_py39.zip)
[an_bluefox_extension_v1_2_windows_py310.zip](https://github.com/harisreedhar/an_bluefox_extension/files/8691950/an_bluefox_extension_v1_2_windows_py310.zip)

**Comment by harisreedhar** [comment]
I don't have windows machine at the moment to check. But it is working fine on linux.
