### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Katyagreat** [harisreedhar/an_bluefox_extension#14]
Blender Version 2.93
Plugin Versionan_bluefox_extension

![Screenshot_2](https://user-images.githubusercontent.com/109244950/178821620-056e205b-6886-43de-9511-aaea3cd88cc9.png)

**Comment by harisreedhar** [comment]
@Katyagreat I haven't found root cause of this problem. For now you can unzip addon and place it manually inside addons folder. Which let you enable addon on preferences.

**Comment by harisreedhar** [comment]
#13

**Comment by harisreedhar** [comment]
For blender version 3.2 or above you can use developmental build:
[Linux](https://github.com/harisreedhar/an_bluefox_extension/releases/download/master-cd-build/an_bluefox_extension_v1_2_linux_py310.zip)
[Mac](https://github.com/harisreedhar/an_bluefox_extension/releases/download/master-cd-build/an_bluefox_extension_v1_2_macOS_py310.zip)
[Windows](https://github.com/harisreedhar/an_bluefox_extension/releases/download/master-cd-build/an_bluefox_extension_v1_2_windows_py310.zip)

**Comment by ondrodoci** [comment]
@harisreedhar Hi, I have the same problem, but it is still not working after unziping addon and placing it manually. I can't enable this addon. I lost two days to fix it and use Spline Tracer node. :/ Any advice is welcome (I am Windows user)

**Comment by harisreedhar** [comment]
@ondrodoci The problem is hopefully fixed. Please try [this build](https://github.com/harisreedhar/an_bluefox_extension/releases/tag/2.93-cd-build).
Make sure to use animation nodes 2.2 & blender 2.93

**Comment by ondrodoci** [comment]
@harisreedhar Thank you! You saved my life, it is working. :)
