### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by meikasahara** [harisreedhar/an_bluefox_extension#18]
Could you please update the addon so that it can be compiled using python3.11, as this is the version used by the newest blender 4.1 alpha builds? Thank you!

The problem seems to be with the falloff nodes. More specifically, removing the noise_4D_falloff.pyx entirely makes the build process complete successfully. You might need to look into recent changes regarding the 4d noise falloff module.

**Comment by Cubism77** [comment]
Also looking for update!

**Comment by Cubism77** [comment]
> Could you please update the addon so that it can be compiled using python3.11, as this is the version used by the newest blender 4.1 alpha builds? Thank you!
> 
> The problem seems to be with the falloff nodes. More specifically, removing the noise_4D_falloff.pyx entirely makes the build process complete successfully. You might need to look into recent changes regarding the 4d noise falloff module.

Hi, can you please share your working version without noise_4d?

**Comment by harisreedhar** [comment]
@Cubism77 @meikasahara Wondering why are you guys using this old addon? I believe Geometry nodes can do these thing very efficiently now🤔

**Comment by meikasahara** [comment]
> > Could you please update the addon so that it can be compiled using python3.11, as this is the version used by the newest blender 4.1 alpha builds? Thank you!
> > The problem seems to be with the falloff nodes. More specifically, removing the noise_4D_falloff.pyx entirely makes the build process complete successfully. You might need to look into recent changes regarding the 4d noise falloff module.
> 
[an_bluefox_extension_v1_2_linux_py311.zip](https://github.com/harisreedhar/an_bluefox_extension/files/14192404/an_bluefox_extension_v1_2_linux_py311.zip)

> Hi, can you please share your working version without noise_4d?

I have compiled it for Linux. Note that the noise_4d still appears in the menu but it does not correspond to anything. I didn't go through the process of removing it from the menu as well, since this was just a test build.

**Comment by Cubism77** [comment]
@harisreedhar Geometry Nodes can't manage rigid bodies. Animation Nodes + your addon is still the easiest way to control RB object procedurally.

**Comment by meikasahara** [comment]
> @Cubism77 @meikasahara Wondering why are you guys using this old addon? I believe Geometry nodes can do these thing very efficiently now🤔

Personally I prefer the approach of Animation Nodes since it is more straightforward to construct and perform direct visualizations on certain computational processes, which, together with this addon, are simpler.

**Comment by harisreedhar** [comment]
@meikasahara @Cubism77 I have added builds for `python 3.11`
see: https://github.com/harisreedhar/an_bluefox_extension/releases/tag/master-cd-build
Iam not following animation_nodes or blender updates these days so not sure about their api changes. So let me know if something is not working.

**Comment by Cubism77** [comment]
@harisreedhar It works great! Thank you very much!!
