### ISSUE TITLE
Cannot to run .pyx files.

### ISSUE THREAD

**Issue by mattbrown0** [harisreedhar/an_bluefox_extension#3]
When starting the program, any .pyx or .pyd file gives an error:

`animation_nodes.data_structures.virtual_list.virtual_clists' has no attribute 'VirtualQuaternionList`

And add-on doesn't work.

**Comment by harisreedhar** [comment]
Can you show full error message? Are you trying to compile yourself?

**Comment by mattbrown0** [comment]
> 
> 
> Can you show full error message? Are you trying to compile yourself?

I have never done a compilation, so I used everything from the release and inserted it into the addon. Single .py node files work, but everything related to compiled files does not work and gives the error that I described earlier. This is the entire text of the error, the rest was cut off. I also looked in the data_structures folder itself and noticed that there really is no such VirtualQuaternionList attribute, if I understood everything correctly.
![изображение](https://user-images.githubusercontent.com/68920871/103102435-05d12f80-462d-11eb-8553-545537c45718.png)

**Comment by harisreedhar** [comment]
> > 
> > 
> > Can you show full error message? Are you trying to compile yourself?
> 
> I have never done a compilation, so I used everything from the release and inserted it into the addon. Single .py node files work, but everything related to compiled files does not work and gives the error that I described earlier. This is the entire text of the error, the rest was cut off. I also looked in the data_structures folder itself and noticed that there really is no such VirtualQuaternionList attribute, if I understood everything correctly.
> ![изображение](https://user-images.githubusercontent.com/68920871/103102435-05d12f80-462d-11eb-8553-545537c45718.png)
> 

Which AN version are you using? Please use latest version. Everything about installation and requirements is explained in the landing page of repository.

**Comment by mattbrown0** [comment]
Yes, it really turned out to be in the add-on version. Thanks for the interesting nodes!

**Comment by harisreedhar** [comment]
> Yes, it really turned out to be in the add-on version. Thanks for the interesting nodes!

Does it work now?
