### ISSUE TITLE
Installation failed on Ubuntu 20.04.1 LTS and Blender 2.91.0

### ISSUE THREAD

**Issue by Derek-K** [harisreedhar/an_bluefox_extension#4]
OS: Ubuntu 20.04.1 LTS
Blender: 2.91.0

Steps to reproduce:
1. Download [Blender 2.91.0-linux64](https://www.blender.org/download/Blender2.91/blender-2.91.0-linux64.tar.xz), unpack it and start.
2. Download and install "AN with BlueFox nodes" - [Linux Build (Python 3.7)](https://github.com/harisreedhar/AN_BLUEFOX/releases/download/AN-bluefox-cd-build/animation_nodes_v2_2_linux_py37.zip)
3. Select the tick box to enable. (optional check version - shows 2.2.1)
4. Download and install "an_bluefox_extension" - [Linux(Python 3.7)](https://github.com/harisreedhar/an_bluefox_extension/releases/download/master-cd-build/an_bluefox_extension_v1_0_linux_py37.zip)

Error when selecting the tick box to enable AN bluefox extension
```
Traceback (most recent call last):
  File "/home/user/Desktop/blender-2.91.0-linux64/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.91/scripts/addons/an_bluefox_extension/__init__.py", line 44, in <module>
    auto_load.init()
  File "/home/user/.config/blender/2.91/scripts/addons/an_bluefox_extension/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/user/.config/blender/2.91/scripts/addons/an_bluefox_extension/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/user/.config/blender/2.91/scripts/addons/an_bluefox_extension/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/home/user/Desktop/blender-2.91.0-linux64/2.91/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "an_bluefox_extension/nodes/color/c_utils.pyx", line 1, in init an_bluefox_extension.nodes.color.c_utils
ValueError: animation_nodes.data_structures.splines.base_spline.Spline size changed, may indicate binary incompatibility. Expected 56 from C header, got 48 from PyObject
```

Tested the same process on Windows 10 (and select the appropriate package) works fine.

**Comment by harisreedhar** [comment]
You don't need to use bluefox build of animation nodes, which is not updated anymore. Using latest animation nodes is recommended.
If you haven't installed libpython on your linux distro please install it ```sudo apt-get install libpython3.7``` and install extension again.

**Comment by Derek-K** [comment]
Thanks for your reply. For some reason, previously I tried to install animation nodes (download from website) it gives me an error, maybe I will try again.

Yes, I have libpython3.7 installed already.

**Comment by Derek-K** [comment]
Tested it again.

1. Removed "an_bluefox_extension".
2. Disabled "Animation nodes", quit blender.
3. Restart blender, remove "Animation nodes". Quit blender.
4. (Optional) Checked ~/.config/blender/2.91/scripts/addons/ with any trace of either add-on
5. Start blender, install "Animation nodes" from [website - Linux - Latest (Python 3.7)](https://github.com/JacquesLucke/animation_nodes/releases/download/master-cd-build/animation_nodes_v2_2_linux_py37.zip)
6. Enable "Anuimation nodes"
7. Install "an_bluefox_extension" and enable it.

No error this time.  Thanks.
