### ISSUE TITLE
Proposal: Marching Cubes option to operate on 2d grid

### ISSUE THREAD

**Issue by meikasahara** [harisreedhar/an_bluefox_extension#6]
Would it be possible to have the option to generate a two-dimensional grid in the Marching Cube node instead of a default 3 dimensional one (for example by giving the user the option to turn on-off one of the three dimensions)  in order to efficiently plot 2d implicit functions? 
As it is currently implemented, if one tries to plot a two dimensional implicit function (with no z dependence), it is evaluated for every grid subdivision in the z dimension, making the computation inefficient, as it appears in the attached screenshot. 
Alternatively, would it be possible for the formula field input to be implemented in the Marching Squares node? 
Thank you.

![image](https://user-images.githubusercontent.com/29499027/110785866-18462700-8274-11eb-8633-55e2573b9a86.png)

**Comment by harisreedhar** [comment]
Hi @meikasahara Thanks for the suggestion. I'll try to add this option when i get time. For now you can use this project file:
[marching_squares_formula.blend.zip](https://github.com/harisreedhar/an_bluefox_extension/files/6127682/marching_squares_formula.blend.zip). It contains a group node which supports formula input for marching squares node.

**Comment by harisreedhar** [comment]
Added individual sample for each axis 553dc928a1d1998ae28918390163fc406b5522e5

**Comment by meikasahara** [comment]
Could you upload an experimental build with the latest updates (python 3.9, linux) ? Thanks!
