### ISSUE TITLE
Spline tracing - Rendering on Renderfarm

### ISSUE THREAD

**Issue by czanimator** [harisreedhar/an_bluefox_extension#8]
Hello,

I'm having an issue with rendering my scene on Render Farm - on multiple machines.

I'm generating a spline traces behind a particle system. Particles are cached. When I splitting the jobs, your AN tracer is starting all the time from the frame PC are starting rendering, from scratch, so tracer doesn't work, basically.

I would need to bake it, somehow? Is the way to do it?

Cheers!

**Comment by harisreedhar** [comment]
@czanimator It is not possible as far as i know, Spline tracer node need to store vector on every execution, which AN doesn't like. If you split frame range data stored in the previous executions are lost.

**Comment by Gerstmann-Bradley** [comment]
I don't have a render farm so I can't test.
Would you try to cache the result in group node and then try to render them in render farm?
![image](https://user-images.githubusercontent.com/55994236/125657516-e00bc0c7-b7e8-46ce-b6c0-98677b9aa7c2.png)

**Comment by harisreedhar** [comment]
@Gerstmann-Bradley  I forgot AN have this option. It will work i think. Thank you.

**Comment by harisreedhar** [comment]
@czanimator You can also convert spline into mesh and save as alembic sequence, if that is possible:

https://user-images.githubusercontent.com/46858047/125736766-1a518e55-eb79-4b52-9697-ba6abb23876c.mp4

**Comment by czanimator** [comment]
Group nodes cache sounds good. I will test it today.

> 
> 
> I don't have a render farm so I can't test.
> Would you try to cache the result in group node and then try to render them in render farm?
> ![image](https://user-images.githubusercontent.com/55994236/125657516-e00bc0c7-b7e8-46ce-b6c0-98677b9aa7c2.png)

**Comment by czanimator** [comment]
@harisreedhar 

ABC cache works like a charm. Thank YOU!
