### ISSUE TITLE
Problems installing your extension

### ISSUE THREAD

**Issue by luckychris** [harisreedhar/an_bluefox_extension#9]
Tried on my macbook:

if i try to install your extension in Blender 3.0:
your extension won't even appear in the add-on list.

If i try to install your extension in Blender 2.93 i got:

![image](https://user-images.githubusercontent.com/232549/133225954-4387c999-9e8e-486b-ba3f-8bcc983fbb4d.png)

![image](https://user-images.githubusercontent.com/232549/133225769-9b303754-318b-454e-bbb0-7e3ce1b63baf.png)

**Comment by harisreedhar** [comment]
@luckychris Looks like you are installing source code not compiled code.
Can you delete files from addon folder manually and reinstall again [this file](https://github.com/harisreedhar/an_bluefox_extension/releases/download/2.93-cd-build/an_bluefox_extension_v1_1_macOS_py39.zip)

**Comment by luckychris** [comment]
i did. exactly the same error.

**Comment by harisreedhar** [comment]
@luckychris The error says ``data_structures.attributes`` module not found. Custom Attributes in AN were added recently. Are you sure using latest animation nodes?

**Comment by luckychris** [comment]
i have 2.2.2. Should i use something else?

**Comment by harisreedhar** [comment]
2.2.2 is 2.93 LTS release and it should run this extension.
I'm not sure why this happens.
I don't have Mac to test myself. These builds are created automatically.

Can you run this ``import animation_nodes as AN; AN.data_structures.attributes`` in blender python console?
If it shows attribute error [reinstall animation nodes](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.2-for-blender-v2.93-cd-build).

**Comment by luckychris** [comment]
i started now blender from the command line and reinstalled AN and after that i could successfully install your add-on. Thank you for your help.
